stages:
    - lint
    - build
    - deploy

lint:
    image: node:12.13.0-alpine
    stage: lint

    script:
        - npm ci
        - npm run lint

build:
    image: node:12.13.0-alpine
    stage: build

    script: 
        - npm ci
        - npm run build
    artifacts:
        paths:
        - build/
        expire_in: 1 day
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
        - node_modules/
        
deploy:
    image: tmaier/docker-compose:18.09
    stage: deploy
    only:
        - master
    script:
        - docker build -t $CI_REGISTRY_IMAGE .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE
    tags:
        - docker-image
