stages:
    - build-image
    - deploy
  
build-reverse-proxy:
    image: tmaier/docker-compose:18.09
    stage: build-image
    only:
      - master
    script:
      - docker build -t $CI_REGISTRY_IMAGE .
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker push $CI_REGISTRY_IMAGE
    tags:
      - docker-image
  
start-compose:
    stage: deploy
    image: tmaier/docker-compose:18.09
    when: manual
    only:
      - master
    script:
      - docker-compose down --remove-orphans
      - docker-compose up -d
    tags:
      - staging
  
stop-compose:
    stage: deploy
    image: tmaier/docker-compose:18.09
    when: manual
    only:
      - master
    script:
      - docker-compose down --remove-orphans
    tags:
      - staging
  
view-logs:
    stage: deploy
    image: tmaier/docker-compose:18.09
    when: manual
    only:
      - master
    script:
      - docker-compose logs
    tags:
      - staging

danger-delete-database:
    stage: deploy
    image: tmaier/docker-compose:18.09
    when: manual
    only:
      - master
    script:
      - docker-compose down --remove-orphans
      - docker volume rm agriary-compose_pgdata
    tags:
      - staging
